name: Cypress Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
# action para rodar os testes do cypress
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - uses: cypress-io/github-action@v7
        with:
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Upload Relatório de Testes  
        uses: actions/upload-artifact@v4
        with:
          name: Relatório de Testes
          path: cypress/reports/html
      


    